### ISSUE TITLE
code

### ISSUE THREAD

**Issue by rootsmusic** [dra2020/vtd_data#1]
@davebradlee Where's the code that produced a state's .csv files?  Thanks.

**Comment by alecramsay** [comment]
The README describes the data sources and processing -- https://github.com/dra2020/vtd_data.

The code itself is (probably) in a combination of [this public repo](https://github.com/dra2020/disagg_agg) and another currently private one. Dave knows the details but he's offline for a few more weeks.

**Comment by rootsmusic** [comment]
Is @davebradlee back?

**Comment by davebradlee** [comment]
It's in a private repo. May become public someday, but not known at this time.
