### ISSUE TITLE
2010 Voting Districts in Kentucky

### ISSUE THREAD

**Issue by christopherkenny** [dra2020/vtd_data#2]
Hello! I was looking at the 2010 data and noticed that [Kentucky](https://github.com/dra2020/vtd_data/blob/master/2010_VTD/KY/2010_census_KY.csv) seems to be at a voting district or precinct level (based on the GEOID pattern), but as far as I know, there were not voting districts in Kentucky last decade. 

For context, there is no block assignment file for Kentucky (FIPS 21) on the [Census's BAF site](https://www.census.gov/geographies/reference-files/time-series/geo/block-assignment-files.2010.html). There is also no shapes listed on [TIGER/Lines site](https://www2.census.gov/geo/tiger/TIGER2010/VTD/2010/) for 2010.

Do you know what geographies the posted data corresponds to?

**Comment by davebradlee** [comment]
At some point in time in 2011, I got the file from someone. I don't remember who. I have a shapefile that I thought was our input for those 2010 shapes in the app, but it appears to be a simplification of the shapes in the app. I would not recommend doing anything important using the 2010 Kentucky shapes and data. Thanks.

**Comment by christopherkenny** [comment]
Thanks @davebradlee, appreciate the quick and helpful response.

**Comment by christopherkenny** [comment]
@davebradlee, FYI, we were able to find shapes that map on in the archives (aka Steve Ansolabehere's closet with old HEDA files). Sharing here in case they are helpful.

[KyPrecincts2010.zip](https://github.com/user-attachments/files/22172252/KyPrecincts2010.zip)
